Traceback (most recent call last):
  File "GUI\Editor.pyo", line 568, in onAsm
  File "GUI\Parser.pyo", line 31, in parse
  File "GUI\Parser.pyo", line 66, in build_commands
  File "shutil.pyo", line 264, in move
  File "shutil.pyo", line 99, in copy2
  File "shutil.pyo", line 52, in copyfile
IOError: [Errno 2] No such file or directory: 'prog_rom.vhd'
Traceback (most recent call last):
  File "GUI\Editor.pyo", line 568, in onAsm
  File "GUI\Parser.pyo", line 31, in parse
  File "GUI\Parser.pyo", line 66, in build_commands
  File "shutil.pyo", line 264, in move
  File "shutil.pyo", line 99, in copy2
  File "shutil.pyo", line 52, in copyfile
IOError: [Errno 2] No such file or directory: 'prog_rom.vhd'
Traceback (most recent call last):
  File "GUI\Editor.pyo", line 568, in onAsm
  File "GUI\Parser.pyo", line 31, in parse
  File "GUI\Parser.pyo", line 66, in build_commands
  File "shutil.pyo", line 264, in move
  File "shutil.pyo", line 99, in copy2
  File "shutil.pyo", line 52, in copyfile
IOError: [Errno 2] No such file or directory: 'prog_rom.vhd'
Traceback (most recent call last):
  File "GUI\Editor.pyo", line 568, in onAsm
  File "GUI\Parser.pyo", line 31, in parse
  File "GUI\Parser.pyo", line 66, in build_commands
  File "shutil.pyo", line 264, in move
  File "shutil.pyo", line 99, in copy2
  File "shutil.pyo", line 52, in copyfile
IOError: [Errno 2] No such file or directory: 'prog_rom.vhd'
Traceback (most recent call last):
  File "GUI\Editor.pyo", line 568, in onAsm
  File "GUI\Parser.pyo", line 31, in parse
  File "GUI\Parser.pyo", line 66, in build_commands
  File "shutil.pyo", line 264, in move
  File "shutil.pyo", line 99, in copy2
  File "shutil.pyo", line 52, in copyfile
IOError: [Errno 2] No such file or directory: 'prog_rom.vhd'
